name: Patch Release APK

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows uploading artifacts to GitHub Releases

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Create google-services.json from secret
      - name: Set up google-services.json
        env:
          ANDROID_GOOGLE_SERVICE: ${{ secrets.ANDROID_GOOGLE_SERVICE }}
        run: echo "$ANDROID_GOOGLE_SERVICE" > app/google-services.json

      # Step 5: Decode the keystore and save it to the app directory
      - name: Set up release keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: echo "$RELEASE_KEYSTORE" | base64 --decode > app/release_keystore.keystore

      # Step 7: Build the Release APK
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew :app:assembleRelease

      # Step 8: Upload APK to GitHub Release
      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/full/release/app-full-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          allowUpdates: true
